apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-config"
data:
  config.yaml: |
    logging:
      # levels: "debug", "info", "warn", "error", "dpanic", "panic", and "fatal"
      level: {{ .Values.config.logLevel }}

    instance_id: {{ .Values.config.instanceId }}

    kafka:
      bootstrap_servers: {{ .Values.config.kafka.servers }}
      topic: {{ .Values.config.kafka.topic }}

    postgres:
      host: {{ .Values.config.postgres.host }}
      port: {{ .Values.config.postgres.port }}
      user: {{ .Values.config.postgres.user }}
      password: {{ .Values.config.postgres.password }}
      db: {{ .Values.config.postgres.db }}
      table: {{ .Values.config.postgres.table }}

    service:
      listen: "0.0.0.0:{{ .Values.config.listenPort }}"