apiVersion: v1
kind: Service
metadata:
  name: {{ include "eventer.fullname" . }}
  labels:
    {{- include "eventer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.config.listenPort }}
      targetPort: {{ .Values.config.listenPort }}
      name: http-eventer
  selector:
    {{- include "eventer.selectorLabels" . | nindent 4 }}
